### ISSUE TITLE
xdai.world上面OmniBridge的链接是不是错了？

### ISSUE THREAD

**Issue by taurenshaman** [DAOSquare/xdai.world#5]
1、通过xdai.world打开OmniBridge是 https://xdai-omnibridge.web.app/ ，跨链后得到的是xdai上面的**DAI**（0x44fA8E6f47987339850636F88629646662444217），也就是截图中的9个币的DAI。
2、通过水龙头（ https://xdai-faucet.top/ ）得到的是xdai上的xdai，截图中有0.01个。
3、通过 https://www.xdaichain.com/ 可以知道OmniBridge的地址是 https://bridge.xdaichain.com/ ，可以通过UI看到跨过去的是xdai而不是DAI。
1和3中的两个OmniBridge的网址不同，但是页面内容基本一样，一个是得到dai，一个是得到xdai。
![2021-08-02 114127](https://user-images.githubusercontent.com/1308706/127801699-fcb37b84-a933-404d-9a85-92cc1c862e09.png)

### 所以：
问题1、xdai.world的OmniBridge链接是不是错了？
问题2、如果没错，怎么在xdai网上把dai换成xdai呢？

**Comment by poria-cat** [comment]
A1. 链接没错
A2. 使用xDai bridge, 也就是导航中OmniBridge旁边的桥
PS. 在使用OminiBridge时可以看到提示:
![image](https://user-images.githubusercontent.com/11287864/127802118-84dc748d-474a-43b7-a2c3-da256d1b04cc.png)
所以OminiBridge不提供dai到xdai的转换, 而是提供其他erc20的转换.
对于已经通过OminiBridge转换的dai, 再次转换到主网即可.
